#ifndef _HEATPUMP_PARAMETERS_H    /* Guard against multiple inclusion */
#define _HEATPUMP_PARAMETERS_H

// Modbus adressen volgens document: M:\Tulip\2023\Tulip Control\TB TC TD protocol V1.2.9.pdf
// REAL TIME DATA 0x0000?0x03F // Nagekeken
#define ADDRESSES_AMOUNT_REAL_TIME_DATA         256       
#define ADDRESS_RUNNING_STATUS_1                0x0000
    #define RUNNING_STATUS_1_SYSTEM_DEFROST_BIT 8
#define ADDRESS_RUNNING_STATUS_2                0x0001
#define ADDRESS_FAULT_STATE_1                   0x0002
#define ADDRESS_FAULT_STATE_2                   0x0003
#define ADDRESS_FAULT_STATE_3                   0x0004
#define ADDRESS_SYSTEM_1_FAULT_STATE_1          0x0005
#define ADDRESS_SYSTEM_1_FAULT_STATE_2          0x0006
#define ADDRESS_SYSTEM_1_DRIVE_FAULT_STATE_1    0x0007
#define ADDRESS_SYSTEM_1_DRIVE_FAULT_STATE_2    0x0008
#define ADDRESS_SYSTEM_1_DRIVE_FAULT_STATE_3    0x0009
#define ADDRESS_SYSTEM_2_FAULT_STATE_1          0x000A
#define ADDRESS_SYSTEM_2_FAULT_STATE_2          0x000B
#define ADDRESS_SYSTEM_2_DRIVE_FAULT_STATE_1    0x000C
#define ADDRESS_SYSTEM_2_DRIVE_FAULT_STATE_2    0x000D
#define ADDRESS_SYSTEM_2_DRIVE_FAULT_STATE_3    0x000E
#define ADDRESS_RELAY_OUTPUT_STATUS_1           0x0019
#define ADDRESS_RELAY_OUTPUT_STATUS_2           0x001A
#define ADDRESS_RELAY_OUTPUT_STATUS_3           0x001B
#define ADDRESS_RELAY_OUTPUT_STATUS_4           0x001C
#define ADDRESS_SWITCH_PORT_STATE_1             0x001D
#define ADDRESS_SWITCH_PORT_STATE_2             0x001E
#define ADDRESS_SWITCH_PORT_STATE_3             0x001F
#define ADDRESS_SWITCH_PORT_STATE_4             0x0020
#define ADDRESS_CURRENT_UNIT_TOOLING_NO         0x0024 
#define ADDRESS_COMPRESSOR_1_TARGET_FREQUENCY   0x0027
#define ADDRESS_COMPRESSOR_2_TARGET_FREQUENCY   0x0028

// REAL TIME DATA 0x0040?0x0FF // Nagekeken
#define ADDRESS_COMPRESSOR_OPERATING_FREQUENCY                 0x0040
#define ADDRESS_FAN_OPERATING_FREQUENCY_ROTATIONAL_SPEED       0x0041
#define ADDRESS_ELECTRONIC_EXPANSION_VALVE_STEPS_COUNT         0x0042
#define ADDRESS_NUMBER_OF_EVI_VALVE_STEPS                      0x0043
#define ADDRESS_AC_INPUT_VOLTAGE                               0x0044
#define ADDRESS_AC_INPUT_CURRENT                               0x0045
#define ADDRESS_COMPRESSOR_PHASE_CURRENT                       0x0046

// Nagekeken
#define ADDRESS_COMPRESSOR_IPM_TEMPERATURE                          0x0047
#define ADDRESS_HIGH_PRESSURE_SATURATION_TEMPERATURE                0x0048
#define ADDRESS_LOW_PRESSURE_SATURATION_TEMPERATURE                 0x0049
#define ADDRESS_EXTERNAL_AMBIENT_TEMPERATURE_T1                     0x004A
#define ADDRESS_EXTERNAL_COIL_TUBE_FIN_T2                           0x004B
#define ADDRESS_INTERNAL_COIL_TUBE_PLATE_REPLACEMENT_T3             0x004C
#define ADDRESS_RETURN_AIR_TEMPERATURE_T4                           0x004D
#define ADDRESS_EXHAUST_TEMPERATURE_T5                              0x004E
#define ADDRESS_RETURN_WATER_TEMPERATURE_T6                         0x004F
#define ADDRESS_WATER_OUTLET_TEMPERATURE_T7                         0x0050
#define ADDRESS_ECONOMIZER_INLET_TUBE_T8                            0x0051
#define ADDRESS_ECONOMIZER_OUTLET_TUBE_T9                           0x0052
#define ADDRESS_CURRENT_DEVICE_TOOLING_NO                           0x0053
#define ADDRESS_WATER_TANK_TEMPERATURE                              0x0054
#define ADDRESS_FLUORINE_OUTLET_TEMPERATURE_OF_PLATE_HEAT_EXCHANGER 0x0055
#define ADDRESS_DRIVE_MANUFACTURER                                  0x0056
#define ADDRESS_PUMP_SPEED_PWM                                      0x0057
#define ADDRESS_WATER_FLOW                                          0x0058
#define ADDRESS_USER_RETURN_WATER_TEMPERATURE                       0x0059
#define ADDRESS_DEVICE_INPUT_VOLTAGE                                0x005A
#define ADDRESS_DEVICE_INPUT_CURRENT                                0x005B
#define ADDRESS_DEVICE_INPUT_POWER_KW                               0x005C
#define ADDRESS_TOTAL_UNIT_ELECTRICITY_CONSUMPTION_KWH              0x005D
#define ADDRESS_SYSTEM_2_COMPRESSOR_RUNNING                         0x005E

// Nagekeken
#define ADDRESS_SYSTEM_2_FAN_RUNNING_FREQUENCY_SPEED                    0x005F
#define ADDRESS_SYSTEM_2_ELECTRONIC_EXPANSION_VALVE_STEPS               0x0060
#define ADDRESS_SYSTEM_2_EVI_VALVE_STEPS                                0x0061
#define ADDRESS_SYSTEM_2_AC_INPUT_VOLTAGE                               0x0062
#define ADDRESS_SYSTEM_2_AC_INPUT_CURRENT                               0x0063
#define ADDRESS_SYSTEM_2_COMPRESSOR_PHASE_CURRENT                       0x0064
#define ADDRESS_SYSTEM_2_COMPRESSOR_IPM_TEMPERATURE                     0x0065
#define ADDRESS_SYSTEM_2_HIGH_PRESSURE_SATURATION_TEMPERATURE           0x0066
#define ADDRESS_SYSTEM_2_LOW_PRESSURE_SATURATION_TEMPERATURE            0x0067
#define ADDRESS_SYSTEM_2_OUTER_COIL_TUBE_FIN                            0x0068
#define ADDRESS_SYSTEM_2_INNER_COIL_TUBE_PLATE_HEAT_EXCHANGER           0x0069
#define ADDRESS_SYSTEM_2_RETURN_AIR_TEMPERATURE                         0x006A
#define ADDRESS_SYSTEM_2_EXHAUST_AIR_TEMPERATURE                        0x006B
#define ADDRESS_SYSTEM_2_ECONOMIZER_INLET_TEMPERATURE                   0x006C
#define ADDRESS_SYSTEM_2_ECONOMIZER_OUTLET_TEMPERATURE                  0x006D
#define ADDRESS_AUXILIARY_HEATING_SOURCE_HOT_WATER_TEMPERATURE_VALUE    0x0072
#define ADDRESS_AUXILIARY_HEATING_SOURCE_HEATING_TEMPERATURE_VALUE      0x0073
#define ADDRESS_BUFFER_TANK_FOR_HEATING_TEMPERATURE_VALUE               0x0074
#define ADDRESS_MAIN_OUTLET_WATER_TEMPERATURE_VALUE                     0x0075
#define ADDRESS_WATER_INLET_TEMPERATURE                                 0x00F0
#define ADDRESS_WATER_OUTLET_TEMPERATURE                                0x00F1
#define ADDRESS_EXTERNAL_ENVIRONMENT_TEMPERATURE                        0x00F2

// Nagekeken
#define ADDRESS_WATER_TANK_TEMPERATURE_2                                            0x00F4
#define ADDRESS_SET_THE_UPPER_LIMIT_OF_FLOOR_HEATING_HEATING_HEATING_TEMPERATURE    0x00FA
#define ADDRESS_SET_THE_LOWER_LIMIT_OF_FLOOR_HEATING_HEATING_HEATING_TEMPERATURE    0x00FB
#define ADDRESS_SET_THE_UPPER_LIMIT_OF_HOT_WATER_TEMPERATURE                        0x00FC
#define ADDRESS_SET_THE_LOWER_LIMIT_OF_HOT_WATER_TEMPERATURE                        0x00FD
#define ADDRESS_SET_THE_UPPER_LIMIT_OF_REFRIGERATING_TEMPERATURE                    0x00FE
#define ADDRESS_SET_THE_LOWER_LIMIT_OF_REFRIGERATING_TEMPERATURE                    0x00FF


// UNIT SYSTEM PARAMETERS 0x0200?0x03FF // Nagekeken
#define ADDRESSES_SYSTEM_PARAMETERS                         512       
#define ADDRESS_T1_EXTERNAL_AMBIENT_TEMPERATURE_SENSOR      0x0100
#define ADDRESS_HIGH_PRESSURE_SWITCH_SETTINGS               0x0101
#define ADDRESS_LOW_PRESSURE_SWITCH_SETTINGS                0x0102
#define ADDRESS_WATER_FLOW_SWITCH_SETTINGS                  0x0103
#define ADDRESS_THERMAL_OVERLOAD_PROTECTION_SWITCH_SETTINGS 0x0104
#define ADDRESS_LINKAGE_SWITCH_SETTINGS                     0x0105
#define ADDRESS_FAN_MOTOR_TYPE_SETTING                      0x0106
#define ADDRESS_HIGH_PRESSURE_PROTECTION_LOCKOUT_SETTING    0x0107
#define ADDRESS_LOW_PRESSURE_PROTECTION_LOCKOUT_SETTING     0x0107
#define ADDRESS_EXHAUST_PROTECTION_LOCKOUT_SETTING          0x0109
#define ADDRESS_WATER_FLOW_SWITCH_PROTECTION_LOCK_SETTING   0x010A
#define ADDRESS_HIGH_PRESSURE_PROTECTION_VALUE              0x010B

// Nagekeken
#define ADDRESS_HIGH_PRESSURE_FREQUENCY_LIMIT_VALUE                                                     0x010C
#define ADDRESS_LOW_PRESSURE_PROTECTION_VALUE                                                           0x010D
#define ADDRESS_LOW_PRESSURE_FREQUENCY_LIMIT_VALUE                                                      0x010E
#define ADDRESS_EXHAUST_TEMPERATURE_PROTECTION_VALUE                                                    0x010F
#define ADDRESS_EXHAUST_TEMPERATURE_LIMIT_FREQUENCY                                                     0x0110
#define ADDRESS_REFRIGERATION_FAN_SPEED_INCREASE_VALUE                                                  0x0111
#define ADDRESS_COOLING_FAN_DECELERATION_VALUE                                                          0x0112
#define ADDRESS_HEATING_FAN_DECELERATION_VALUE                                                          0x0113
#define ADDRESS_HEATING_FAN_SPEED_INCREASE_VALUE                                                        0x0114
#define ADDRESS_UNIT_PROHIBITS_STARTING_LOW_TEMPERATURE_VALUE                                           0x0115
#define ADDRESS_ELECTRIC_HEATING_START_AMBIENT_TEMPERATURE_VALUE                                        0x0116
#define ADDRESS_TEMPERATURE_DIFFERENCE_BETWEEN_THE_INLET_AND_OUTLET_WATER_EXCEEDS_THE_THRESHOLD_VALUE   0x0117
#define ADDRESS_RETURN_WATER_TEMPERATURE_COMPENSATION_VALUE                                             0x0118
#define ADDRESS_OUTLET_WATER_TEMPERATURE_COMPENSATION_VALUE                                             0x0119
#define ADDRESS_AIR_CONDITIONER_RETURN_DIFFERENCE                                                       0x011A
#define ADDRESS_FLOOR_HEATING_DIFFERENCE                                                                0x011B
#define ADDRESS_PUMP_CONTROL_MODE_WHEN_THE_DEVICE_REACHING_TARGET_TEMPERATURE_AND_SHUTDOWN              0x011C
#define ADDRESS_ANTIFREEZE_WATER_PUMP_RUNNING_TIME_EVERY_10MIN                                          0x011D
#define ADDRESS_DEFROST_MODE_SELECTION                                                                  0x011E
#define ADDRESS_DEFROST_ACCUMULATED_RUNNING_TIME_THRESHOLD_VALUE                                        0x011F
#define ADDRESS_DEFROST_COIL_TEMPERATURE_VALUE                                                          0x0120
#define ADDRESS_DEFROST_TEMPERATURE_DIFFERENCE_1                                                        0x0121
#define ADDRESS_DEFROST_TEMPERATURE_DIFFERENCE_2                                                        0x0122
#define ADDRESS_MAX_DEFROST_TIME                                                                        0x0123
#define ADDRESS_EXIT_DEFROST_COIL_TEMPERATURE                                                           0x0124
#define ADDRESS_DEVICE_REACHING_TARGET_TEMPERATURE_AND_SHUTDOWN_MODE                                    0x0125
#define ADDRESS_HEATING_MAIN_VALVE_INITIAL_OPENING_CONSTANT                                             0x0126
#define ADDRESS_PRESSURE_SENSOR_SETTINGS                                                                0x0127
#define ADDRESS_COOLING_TARGET_SUPERHEAT_CORRECTION_VALUE                                               0x0128
#define ADDRESS_HEATING_HIGH_PRESSURE_PROTECTION_AND_FREQUENCY_LIMIT_CORRECTION_VALUE                   0x0129

// Nagekeken
#define ADDRESS_HEATING_TARGET_SUPERHEAT_CORRECTION_VALUE                               0x012A
#define ADDRESS_MEDIUM_PRESSURE_SWITCH_SETTINGS                                         0x012B
#define ADDRESS_WATER_FLOW_SWITCH_FAILURE_DETECTION_SETTINGS                            0x012C
#define ADDRESS_COMMUNICATION_ADDRESS_CODE                                              0x012D
#define ADDRESS_RETURN_DIFFERENCE_OF_THE_OPENING_OF_THE_LIQUID_INJECTION_SOLENOID_VALVE 0x012E
#define ADDRESS_EVI_TARGET_SUPERHEAT_CONSTANT                                           0x012F
#define ADDRESS_TANK_TEMPERATURE_PROBE_ENABLED                                          0x0130
    #define TANK_TEMPERATURE_PROBE_DISABLED                                             0
    #define TANK_TEMPERATURE_PROBE_ENABLED                                              1
#define ADDRESS_HOT_WATER_FREQUENCY_OPERATING_PERCENTAGE                                0x0131
#define ADDRESS_COOLING_TARGET_FREQUENCY_CONSTANT_A                                     0x0132
#define ADDRESS_COOLING_MINIMUM_FREQUENCY_LIMIT                                         0x0133
#define ADDRESS_COOLING_TARGET_FREQUENCY_UPPER_LIMIT                                    0x0134
#define ADDRESS_COOLING_TARGET_FREQUENCY_LOWER_LIMIT                                    0x0135
#define ADDRESS_HEATING_TARGET_FREQUENCY_CONSTANT_B                                     0x0136
#define ADDRESS_HEATING_TARGET_FREQUENCY_UPPER_LIMIT                                    0x0137
#define ADDRESS_HEATING_TARGET_FREQUENCY_LOWER_LIMIT                                    0x0138
#define ADDRESS_HEATING_MINIMUM_FREQUENCY_1                                             0x0139
#define ADDRESS_HEATING_MINIMUM_FREQUENCY_2                                             0x013A
#define ADDRESS_HEATING_MINIMUM_FREQUENCY_3                                             0x013B
#define ADDRESS_HOT_WATER_TARGET_FREQUENCY_CONSTANT_B                                   0x013C
#define ADDRESS_HOT_WATER_TARGET_FREQUENCY_UPPER_LIMIT_VALUE                            0x013D
#define ADDRESS_HOT_WATER_TARGET_FREQUENCY_LOWER_LIMIT_VALUE                            0x013E
#define ADDRESS_HOT_WATER_MINIMUM_FREQUENCY_1                                           0x013F
#define ADDRESS_HOT_WATER_MINIMUM_FREQUENCY_2                                           0x0140
#define ADDRESS_HOT_WATER_MINIMUM_FREQUENCY_3                                           0x0141
#define ADDRESS_DC_FAN_INITIAL_FREQUENCY                                                0x0142
#define ADDRESS_DC_FAN_HEATING_MINIMUM_FREQUENCY                                        0x0143
#define ADDRESS_DC_FAN_HEATING_MAXIMUM_FREQUENCY                                        0x0144
#define ADDRESS_DC_FAN_COOLING_MINIMUM_FREQUENCY                                        0x0145
#define ADDRESS_DC_FAN_COOLING_MAXIMUM_FREQUENCY                                        0x0146
#define ADDRESS_TURN_ON_ENTHALPY_CONTROL_FREQUENCY                                      0x0147
#define ADDRESS_STOP_ENTHALPY_INCREASE_FREQUENCY                                        0x0148
#define ADDRESS_REFRIGERATION_MAIN_VALVE_INITIAL_OPENING_1                              0x0149
#define ADDRESS_REFRIGERATION_MAIN_VALVE_INITIAL_OPENING_2                              0x014A
#define ADDRESS_REFRIGERATION_MAIN_VALVE_INITIAL_OPENING_3                              0x014B
#define ADDRESS_MINIMUM_OPENING_OF_REFRIGERATION_MAIN_VALVE                             0x014C
#define ADDRESS_MINIMUM_OPENING_OF_HEATING_MAIN_VALVE                                   0x014D
#define ADDRESS_MAIN_VALVE_MAXIMUM_OPENING                                              0x014E
#define ADDRESS_MAIN_VALVE_INITIAL_OPENING_CONSTANT_C                                   0x014F
#define ADDRESS_MAIN_VALVE_INITIAL_OPENING_COEFFICIENT_A                                0x0150
#define ADDRESS_MAIN_VALVE_INITIAL_OPENING_COEFFICIENT_B                                0x0151

// Nagekeken
#define ADDRESS_AUXILIARY_VALVE_MAXIMUM_OPENING                     0x0152
#define ADDRESS_AUXILIARY_VALVE_MINIMUM_OPENING                     0x0153
#define ADDRESS_MAIN_VALVE_REGULATION_PERIOD                        0x0154
#define ADDRESS_AUXILIARY_VALVE_INITIAL_OPENING_CONSTANT_C          0x0155
#define ADDRESS_AUXILIARY_VALVE_INITIAL_OPENING_COEFFICIENT_A       0x0156
#define ADDRESS_AUXILIARY_VALVE_INITIAL_OPENING_COEFFICIENT_B       0x0157
#define ADDRESS_SILENT_MODE_COMPRESSOR_FREQUENCY                    0x0158
#define ADDRESS_QUIET_MODE_FAN_FREQUENCY                            0x0159
#define ADDRESS_AMBIENT_TEMPERATURE_TO_ENTER_EVI                    0x015A
#define ADDRESS_TIME_TO_FORBIT_ENTERING_INTO_EVI_TIME               0x015B
#define ADDRESS_TEMPERATURE_DIFFERENCE_TO_ENTER_EVI                 0x015C
#define ADDRESS_COMPRESSOR_CONTINUOUS_RUNNING_TIME_TO_ENTER_EVI     0x015D
#define ADDRESS_AUXILIARY_VALVE_ADJUSTMENT_CYCLE                    0x015E
#define ADDRESS_CASCADE_WATER_PUMP_RUNNING_MODE                     0x015F
#define ADDRESS_HOT_WATER_RETURN_DIFFERENCE                         0x0160
#define ADDRESS_WATER_TANK_TEMPERATURE_AUTOMATIC_COMPENSATION       0x0161
#define ADDRESS_MANUAL_COMPENSATION_VALUE_OF_WATER_TANK_TEMPERATURE 0x0162
#define ADDRESS_PUMP_SPEED_CONTROL_TEMPERATURE_DIFFERENCE           0x0163
#define ADDRESS_PWM_WATER_PUMP_MINIMUM_SPEED                        0x0164
#define ADDRESS_PUMP_CONTROL_MODE                                   0x0165
#define ADDRESS_FOUR_WAY_VALVE_CONTROL_MODE                         0x0166
#define ADDRESS_MODE_SWITCHING_MINIMUM_RUNTIME                      0x0167
#define ADDRESS_OPERATING_FREQUENCY_PERCENTAGE_WHEN_SWITCHING_MODES 0x0168
#define ADDRESS_COOLING_MODE_OPERATING_AMBIENT_TEMPERATURE_LIMIT    0x0169
#define ADDRESS_HEATING_MODE_OPERATING_AMBIENT_TEMPERATURE_LIMIT    0x016A
#define ADDRESS_HOT_WATER_MODE_OPERATING_AMBIENT_TEMPERATURE_LIMIT  0x016B
#define ADDRESS_HOT_WATER_SETTING_TEMPERATURE_UPPER_LIMIT           0x016C
#define ADDRESS_HOT_WATER_SETTING_TEMPERATURE_LOWER_LIMIT           0x016D
#define ADDRESS_HEATING_SET_TEMPERATURE_UPPER_LIMIT                 0x016E
#define ADDRESS_HEATING_SET_TEMPERATURE_LOWER_LIMIT                 0x016F
#define ADDRESS_COOLING_SET_TEMPERATURE_UPPER_LIMIT                 0x0170
#define ADDRESS_COOLING_SET_TEMPERATURE_LOWER_LIMIT                 0x0171
#define ADDRESS_SELECTION_OF_THE_NUMBER_OF_COMPRESSOR               0x0172
#define ADDRESS_MODEL_SELECTION                                     0x0173

// Nagekeken
#define ADDRESS_UNIT_TEMPERATURE_CONTROL_METHOD                     0x0174
    #define UNIT_TEMPERATURE_CONTROL_METHOD_RETURN_WATER            0
    #define UNIT_TEMPERATURE_CONTROL_METHOD_WATER_OUTLET            1
#define ADDRESS_AMBIENT_TEMPERATURE_TO_ENTER_ANTIFREEZE_MODE        0x0175
#define ADDRESS_ANTIFREEZE_INLET_AND_OUTLET_WATER_TEMPERATURE       0x0176
#define ADDRESS_REFRIGERANT_TYPE                                    0x0177
#define ADDRESS_LOW_TEMPERATURE_START_LIMIT                         0x0178
#define ADDRESS_HEATING_FREQUENCY_SHIELD_1_STAGE_LOW_VALUE          0x0179
#define ADDRESS_HEATING_FREQUENCY_SHIELD_1_STAGE_HIGH_VALUE         0x017A
#define ADDRESS_HEATING_FREQUENCY_SHIELD_2_STAGE_LOW_VALUE          0x017B
#define ADDRESS_HEATING_FREQUENCY_SHIELD_2_STAGE_HIGH_VALUE         0x017C
#define ADDRESS_HEATING_FREQUENCY_SHIELD_3_STAGE_LOW_VALUE          0x017D
#define ADDRESS_HEATING_FREQUENCY_SHIELD_3_STAGE_HIGH_VALUE         0x017E
#define ADDRESS_COOLING_FREQUENCY_SHIELD_1_STAGE_LOW_VALUE          0x017F
#define ADDRESS_COOLING_FREQUENCY_SHIELD_1_STAGE_HIGH_VALUE         0x0180
#define ADDRESS_COOLING_FREQUENCY_SHIELD_2_STAGE_LOW_VALUE          0x0181
#define ADDRESS_COOLING_FREQUENCY_SHIELD_2_STAGE_HIGH_VALUE         0x0182
#define ADDRESS_COOLING_FREQUENCY_SHIELD_3_STAGE_LOW_VALUE          0x0183
#define ADDRESS_COOLING_FREQUENCY_SHIELD_3_STAGE_HIGH_VALUE         0x0184
#define ADDRESS_FAN_MODULE                                          0x0185
#define ADDRESS_WATER_FLOW_IS_TOO_LOW_PROTECTION_VALUE              0x0186
#define ADDRESS_TEMPERATURE_DIFFERENCE_TO_START_ANTI_CONDENSATION   0x0187
#define ADDRESS_AMBIENT_TEMPERATURE_TO_OPEN_THROTTLE_BYPASS_VALVE   0x0188
#define ADDRESS_THROTTLE_BYPASS_VALVE_DELAY_COMPRESSOR              0x0189
#define ADDRESS_DEFROST_COMPRESSOR_FREQUENCY                        0x018A
#define ADDRESS_AIR_CONDITIONING_ELECTRIC_HEATING_OPTIONS           0x018B
#define ADDRESS_HOT_WATER_ELECTRIC_HEATING_OPTIONS                  0x018C
#define ADDRESS_DEW_POINT_DURATION_OF_DEFROST                       0x018D
#define ADDRESS_DEW_POINT_CONSTANT_OF_DEFROST                       0x018E
#define ADDRESS_WATER_TEMPERATURE_TO_ENTER_DEFROST_MODE             0x018F
#define ADDRESS_AMBIENT_TEMPERATURE_TO_ENTER_DEFROST_MODE           0x0190
#define ADDRESS_WATER_OUTLET_ANTIFREEZE_PROTECTION_VALUE            0x0191
#define ADDRESS_PUMP_RANGE_SETTING_VALUE                            0x0192
#define ADDRESS_COOLING_ANTI_FREEZE_MODE                            0x0193
#define ADDRESS_COOLING_ANTI_FREEZE_TEMPERATURE_VALUE               0x0194
#define ADDRESS_WATER_OUT_OF_THE_HIGH_LIMIT_FREQUENCY_VALUE         0x0195
#define ADDRESS_SECONDARY_HEATING_PUMP_SELECTION                    0x0196
#define ADDRESS_HOT_WATER_HEAT_SOURCE_RETURN_DIFFERENCE             0x0197
#define ADDRESS_HEATING_HEAT_SOURCE_RETURN_DIFFERENCE               0x0198

// Nagekeken
#define ADDRESS_COMBINED_HOT_WATER_HEAT_SOURCE_UPPER_TEMPERATURE_LIMIT                      0x0199
#define ADDRESS_COMBINED_HEATING_HEAT_SOURCE_UPPER_TEMPERATURE_LIMIT                        0x019A
#define ADDRESS_COMPRESSOR_CODE_FUNCTION_RESERVED                                           0x019B
#define ADDRESS_AUXILIARY_ELECTRONIC_EXPANSION_VALVE_SELECTION                              0x019C
#define ADDRESS_AUXILIARY_ELECTRONIC_EXPANSION_VALVE_TO_REDUCE_THE_TEMPERATURE_DIFFERENCE   0x019D
#define ADDRESS_HEATING_LIMIT_WATER_TEMPERATURE_START_THE_AMBIENT_TEMPERATURE               0x019E
#define ADDRESS_LIMIT_TEMPERATURE_CONSTANT_P159                                             0x019F
#define ADDRESS_LIMIT_TEMPERATURE_COEFFICIENT_P160                                          0x01A0
#define ADDRESS_AUXILIARY_PUMP_SELECTION                                                    0x01A1
#define ADDRESS_ANTI_FREEZING_INTERVAL_FOR_HOT_WATER_PIPES                                  0x01A2
#define ADDRESS_MINIMUM_FEEDBACK_OF_PUMP_SPEED_REGULATION                                   0x01A3
#define ADDRESS_LEVEL_CONTROL                                                               0x01A4
#define ADDRESS_LOAD_RETURN_DIFFERENCE                                                      0x01A5
#define ADDRESS_LOAD_SHEDDING_HYSTERESIS                                                    0x01A6
#define ADDRESS_EMERGENCY_STOP_RETURN_DIFFERENCE                                            0x01A7
#define ADDRESS_HOT_WATER_MODE_START_RATIO                                                  0x01A8
#define ADDRESS_NON_HOT_WATER_MODE_START_RATIO                                              0x01A9
#define ADDRESS_LOADING_CYCLE                                                               0x01AA
#define ADDRESS_SHIELD_LOW_VOLTAGE_SWITCH_AMBIENT_TEMPERATURE                               0x01AB
#define ADDRESS_TARGET_FREQUENCY_CONSTANT_C_OF_DC_FAN                                       0x01AC
#define ADDRESS_TARGET_FREQUENCY_OF_HEATING_FAN_LOWER_LIMIT                                 0x01AD
#define ADDRESS_DEFROST_VALVE_OPENING                                                       0x01AE
#define ADDRESS_CONSTANT_TEMPERATURE_OPERATION_CYCLE                                        0x01AF
#define ADDRESS_MINIMUM_DEFROSTING_TIME                                                     0x01B0
#define ADDRESS_DEFROST_SEGMENTED_WATER_TEMPERATURE_SETTING_VALUE                           0x01B1
#define ADDRESS_HIGH_WATER_TEMPERATURE_DEFROSTING_FREQUENCY                                 0x01B2
#define ADDRESS_STRONG_MODE_FREQUENCY_INCREASE_VALUE                                        0x01B3
#define ADDRESS_POWERFUL_MODE_FREQUENCY_CAP_INCREASE_VALUE                                  0x01B4
#define ADDRESS_DEFROST_MODE                                                                0x01B5
#define ADDRESS_PIPE_ELECTRIC_HEATING_OPTION                                                0x01B6
#define ADDRESS_PARAMETER_PASSWORD_SETTING                                                  0x01B7
#define ADDRESS_35D_WORKING_CONDITION_COMPRESSOR_FREQUENCY                                  0x01B8

// Nagekeken    
#define ADDRESS_35C_WORKING_CONDITION_COMPRESSOR_FREQUENCY              0x01B9
#define ADDRESS_35B_WORKING_CONDITION_COMPRESSOR_FREQUENCY              0x01BA
#define ADDRESS_35A_WORKING_CONDITION_COMPRESSOR_FREQUENCY              0x01BB
#define ADDRESS_35E_WORKING_CONDITION_COMPRESSOR_FREQUENCY              0x01BC
#define ADDRESS_55D_WORKING_CONDITION_COMPRESSOR_FREQUENCY              0x01BD
#define ADDRESS_55C_WORKING_CONDITION_COMPRESSOR_FREQUENCY              0x01BE
#define ADDRESS_55B_WORKING_CONDITION_COMPRESSOR_FREQUENCY              0x01BF
#define ADDRESS_55A_WORKING_CONDITION_COMPRESSOR_FREQUENCY              0x01C0
#define ADDRESS_55E_WORKING_CONDITION_COMPRESSOR_FREQUENCY              0x01C1
#define ADDRESS_35D_WORKING_CONDITION_FAN_FREQUENCY                     0x01C2
#define ADDRESS_35C_WORKING_CONDITION_FAN_FREQUENCY                     0x01C3
#define ADDRESS_35B_WORKING_CONDITION_FAN_FREQUENCY                     0x01C4
#define ADDRESS_35A_WORKING_CONDITION_FAN_FREQUENCY                     0x01C5
#define ADDRESS_35E_WORKING_CONDITION_FAN_FREQUENCY                     0x01C6
#define ADDRESS_55D_WORKING_CONDITION_FAN_FREQUENCY                     0x01C7
#define ADDRESS_55C_WORKING_CONDITION_FAN_FREQUENCY                     0x01C8
#define ADDRESS_55B_WORKING_CONDITION_FAN_FREQUENCY                     0x01C9
#define ADDRESS_55A_WORKING_CONDITION_FAN_FREQUENCY                     0x01CA
#define ADDRESS_55E_WORKING_CONDITION_FAN_FREQUENCY                     0x01CB
#define ADDRESS_35D_OPERATING_CONDITION_MAIN_VALVE_TARGET_SUPERHEAT     0x01CC
#define ADDRESS_35C_WORKING_CONDITION_MAIN_VALVE_TARGET_SUPERHEAT       0x01CD
#define ADDRESS_35B_WORKING_CONDITION_MAIN_VALVE_TARGET_SUPERHEAT       0x01CE
#define ADDRESS_35A_WORKING_CONDITION_MAIN_VALVE_TARGET_SUPERHEAT       0x01CF
#define ADDRESS_35E_WORKING_CONDITION_MAIN_VALVE_TARGET_SUPERHEAT       0x01D0
#define ADDRESS_55D_OPERATING_CONDITION_MAIN_VALVE_TARGET_SUPERHEAT     0x01D1
#define ADDRESS_55C_OPERATING_CONDITION_MAIN_VALVE_TARGET_SUPERHEAT     0x01D2
#define ADDRESS_55B_WORKING_CONDITION_MAIN_VALVE_TARGET_SUPERHEAT       0x01D3
#define ADDRESS_TARGET_SUPERHEAT_OF_MAIN_VALVE_IN_55A_WORKING_CONDITION 0x01D4
#define ADDRESS_55E_WORKING_CONDITION_MAIN_VALVE_TARGET_SUPERHEAT       0x01D5
#define ADDRESS_35D_INITIAL_OPENING_OF_MAIN_VALVE                       0x01D6
#define ADDRESS_35C_INITIAL_OPENING_OF_MAIN_VALVE                       0x01D7
#define ADDRESS_35B_INITIAL_OPENING_OF_MAIN_VALVE                       0x01D8
#define ADDRESS_35A_INITIAL_OPENING_OF_MAIN_VALVE                       0x01D9
#define ADDRESS_35E_INITIAL_OPENING_OF_MAIN_VALVE                       0x01DA
#define ADDRESS_55D_INITIAL_OPENING_OF_MAIN_VALVE                       0x01DB
#define ADDRESS_55C_INITIAL_OPENING_OF_MAIN_VALVE                       0x01DC
#define ADDRESS_55B_INITIAL_OPENING_OF_MAIN_VALVE                       0x01DD
#define ADDRESS_55A_INITIAL_OPENING_OF_MAIN_VALVE                       0x01DE

// Nagekeken
#define ADDRESS_INITIAL_OPENING_OF_MAIN_VALVE_IN_55E_WORKING_CONDITION          0x01DF
#define ADDRESS_35D_OPERATING_CONDITION_AUXILIARY_VALVE_TARGET_SUPERHEAT        0x01E0
#define ADDRESS_35C_OPERATING_CONDITION_AUXILIARY_VALVE_TARGET_SUPERHEAT        0x01E1
#define ADDRESS_35B_OPERATING_CONDITION_AUXILIARY_VALVE_TARGET_SUPERHEAT        0x01E2
#define ADDRESS_35A_WORKING_CONDITION_AUXILIARY_VALVE_TARGET_SUPERHEAT          0x01E3
#define ADDRESS_35E_WORKING_CONDITION_AUXILIARY_VALVE_TARGET_SUPERHEAT          0x01E4
#define ADDRESS_55D_WORKING_CONDITION_AUXILIARY_VALVE_TARGET_SUPERHEAT          0x01E5
#define ADDRESS_55C_WORKING_CONDITION_AUXILIARY_VALVE_TARGET_SUPERHEAT          0x01E6
#define ADDRESS_AUXILIARY_VALVE_TARGET_SUPERHEAT_IN_55B_WORKING_CONDITION       0x01E7
#define ADDRESS_AUXILIARY_VALVE_TARGET_SUPERHEAT_IN_55A_WORKING_CONDITION       0x01E8
#define ADDRESS_AUXILIARY_VALVE_TARGET_SUPERHEAT_IN_55E_WORKING_CONDITION       0x01E9
#define ADDRESS_INITIAL_OPENING_OF_AUXILIARY_VALVE_IN_35D_WORKING_CONDITION     0x01EA
#define ADDRESS_INITIAL_OPENING_OF_AUXILIARY_VALVE_IN_35C_WORKING_CONDITION     0x01EB
#define ADDRESS_INITIAL_OPENING_OF_AUXILIARY_VALVE_IN_35B_WORKING_CONDITION     0x01EC
#define ADDRESS_INITIAL_OPENING_OF_AUXILIARY_VALVE_IN_35A_WORKING_CONDITION     0x01ED
#define ADDRESS_INITIAL_OPENING_OF_AUXILIARY_VALVE_IN_35E_WORKING_CONDITION     0x01EE
#define ADDRESS_INITIAL_OPENING_OF_AUXILIARY_VALVE_IN_55D_WORKING_CONDITION     0x01EF
#define ADDRESS_INITIAL_OPENING_OF_AUXILIARY_VALVE_IN_55C_WORKING_CONDITION     0x01F0
#define ADDRESS_INITIAL_OPENING_OF_AUXILIARY_VALVE_IN_55B_WORKING_CONDITION     0x01F1
#define ADDRESS_INITIAL_OPENING_OF_AUXILIARY_VALVE_IN_55A_WORKING_CONDITION     0x01F2
#define ADDRESS_INITIAL_OPENING_OF_AUXILIARY_VALVE_IN_55E_WORKING_CONDITION     0x01F3
#define ADDRESS_TARGET_WATER_FLOW_IN_35_LOW_WATER_TEMPERATURE_CONDITION         0x01F4
#define ADDRESS_TARGET_WATER_FLOW_UNDER_55_HIGH_WATER_TEMPERATURE_CONDITIONS    0x01F5
#define ADDRESS_35_LOW_WATER_TEMPERATURE_RATED_FAN_FREQUENCY                    0x01F6

// Nagekeken
#define ADDRESS_INITIAL_OPENING_OF_MAIN_VALVE_UNDER_35_LOW_WATER_TEMPERATURE_RATED_CONDITION    0x01F7
#define ADDRESS_INITIAL_OPENING_OF_MAIN_VALVE_UNDER_55_HIGH_WATER_TEMPERATURE_RATED_CONDITION   0x01F8
#define ADDRESS_INITIAL_OPENING_OF_MAIN_VALVE_UNDER_55_HIGH_WATER_TEMPERATURE_RATED_CONDITION_P 0x01F9
#define ADDRESS_TARGET_SUPERHEAT_OF_MAIN_VALVE_UNDER_35_LOW_WATER_TEMPERATURE_RATED_CONDITION   0x01FA
#define ADDRESS_PFC_SHUTDOWN_CURRENT                                                            0x01FB
#define ADDRESS_TARGET_SUPERHEAT_OF_MAIN_VALVE_UNDER_55_HIGH_WATER_TEMPERATURE_RATED_CONDITION  0x01FC
#define ADDRESS_PFC_TURN_ON_CURRENT                                                             0x01FD
#define ADDRESS_HEATING_MEDIUM                                                                  0x01FE
#define ADDRESS_SMART_GRID_OPTIONS                                                              0x01FF
#define ADDRESS_PEAK_GRID_RUNNING_TIME                                                          0x0200
#define ADDRESS_DUAL_TEMPERATURE_ZONE_SELECTION                                                 0x0201
#define ADDRESS_MIXED_WATER_REGULATING_VALVE_CYCLE                                              0x0202
#define ADDRESS_MIXING_VALVE_FULL_CYCLE_TIME                                                    0x0203
#define ADDRESS_MAX_ROTATE_SPEED_OF_DC_WATER_PUMP                                               0x0204
#define ADDRESS_ROTATE_SPEED_OF_DC_WATER_PUMP_UNDER_CONSTANT_TEMPERATURE                        0x0205
#define ADDRESS_FLOOR_HEATING_TEST_MODE_SELECTION                                               0x0206

// USER PARAMETERS 0x0300?0x032F // Nagekeken
#define ADDRESSES_USER_PARAMETERS                   112      
#define ADDRESS_COOLING_SET_TEMPERATURE             0x0300
#define ADDRESS_HEATING_SET_TEMPERATURE             0x0301
#define ADDRESS_HOT_WATER_SET_TEMPERATURE           0x0302
#define ADDRESS_FLOOR_HEATING_SET_TEMPERATURE       0x0303
#define ADDRESS_SET_MODE                            0x0304
    #define SET_MODE_COOLING                        0
    #define SET_MODE_HEATING                        1
    #define SET_MODE_HOT_WATER                      2
    #define SET_MODE_FLOOR_HEATING                  3
    #define SET_MODE_HOT_WATER_AND_COOLING          4
    #define SET_MODE_HOT_WATER_AND_HEATING          5
    #define SET_MODE_RESERVE                        6
    #define SET_MODE_HOT_WATER_AND_FLOOR_HEATING    7
#define ADDRESS_ON_OFF                              0x0305
    #define SET_HEATPUMP_OFF                        0
    #define SET_HEATPUMP_ON                         1
#define ADDRESS_INDOOR_TEMPERATURE_SET_POINT        0x0306
#define ADDRESS_FREQUENCY_CONVERSION_MODE           0x0307
#define ADDRESS_DISPLAY_TIME                        0x0309
#define ADDRESS_FUNCTIONAL_MODE                     0x030A
#define ADDRESS_HEATING_FLOOR_HEATING_CURVE_SETTING 0x030C
    #define HEATING_CURVE_SETTING_OFF 0 
#define ADDRESS_HOT_WATER_COOLING_CURVE_SETTINGS    0x030D
#define ADDRESS_COOLING_CURVE_SETTING               0x0313
#define ADDRESS_HEATING_CURVE_SETTING               0x0314
#define ADDRESS_HOT_WATER_CURVE_SETTING             0x0315
#define ADDRESS_FLOOR_HEATING_CURVE_SETTING         0x0316

// User Order Parameters 0x0330?0x035F // Nagekeken
#define ADDRESS_CREW_CONTROL                        0x0330
#define ADDRESS_LOAD_FORCED_CONTROL                 0x0331
#define ADDRESS_COMPRESSOR_1_FORCED_FREQUENCY       0x0332
#define ADDRESS_COMPRESSOR_2_FORCED_FREQUENCY       0x0333
#define ADDRESS_EEV1_FORCED_OPENING                 0x0336
#define ADDRESS_EEV2_FORCED_OPENING                 0x0337
#define ADDRESS_EVI1_FORCED_OPENING                 0x033A
#define ADDRESS_EVI2_FORCED_OPENING                 0x033B
#define ADDRESS_FAN_MOTOR_FORCED_SPEED              0x033E
#define ADDRESS_DC_WATER_PUMP_CONTROL               0x0343
#define ADDRESS_DC_WATER_PUMP_OUTPUT                0x0344
#define ADDRESS_PFC_CONTROL                         0x0345

// Version Information Parameters 0x0360?0x036F // Nagekeken
#define ADDRESS_PROGRAM_VERSION                     0x0360
#define ADDRESS_PRODUCT_TYPE                        0x0361
#define ADDRESS_PRODUCT_TYPE_IDENTIFICATION_NUMBER  0x0362
#define ADDRESS_PROTOCOL_VERSION                    0x0363

// Unit System Parameters L 0x0800?0x083F // Nagekeken
#define ADDRESSES_UNIT_SYSTEM_PARAMETERS                    64
#define ADDRESS_PIPE_ELECTRICITY_HEATING_LOADING_TIME       0x0800
#define ADDRESS_HIGH_TEMPERATURE_STERILIZATION_FUNCTION     0x0801
    #define STERILIZATION_FUNCTION_AUTO                     0
    #define STERILIZATION_FUNCTION_DISABLE                  1
    #define STERILIZATION_FUNCTION_MANUAL                   2
#define ADDRESS_STERILIZATION_INTERVAL_DAYS                 0x0802
#define ADDRESS_STERILIZATION_START_TIME                    0x0803
#define ADDRESS_STERILIZATION_RUN_TIME                      0x0804
#define ADDRESS_STERILIZATION_TEMPERATURE_SETTING           0x0805
#define ADDRESS_RETURN_WATER_MODE                           0x080B
#define ADDRESS_RETURN_WATER_SET_TEMPERATURE                0x080C
#define ADDRESS_RETURN_WATER_TEMPERATURE_RETURN_DIFFERENCE  0x080D
#define ADDRESS_RETURN_WATER_CYCLE                          0x080E
#define ADDRESS_RETURN_WATER_TIME                           0x080F

// Coils address 0X1000-0X10FF // Nagekeken
#define ADDRESSES_COILS_ADDRESSES               256                 
#define ADDRESS_HIGH_POWER_MODE_ADDRESS         0x1000
#define ADDRESS_SILENT_MODE                     0x1001
#define ADDRESS_FAST_HEATING_MODE               0x1012
#define ADDRESS_FORCED_INTO_DEFROST             0x1013
#define ADDRESS_SYSTEM_EMPTYING_MODE            0x1014
#define ADDRESS_REFRIGERANT_RECOVERY            0x1015
#define ADDRESS_FORCED_INTO_STERILIZING         0x1018
#define ADDRESS_ALLOW_WATER_BACK                0x101A
#define ADDRESS_RESTORE_FACTORY_DEFAULTS        0x101D
#define ADDRESS_COMPRESSOR_FORCED_TO_CONTROL    0x1020
#define ADDRESS_EEV_FORCED_TO_CONTROL           0x1021
#define ADDRESS_EVI_FORCED_TO_CONTROL           0x1022
#define ADDRESS_FAN_MOTOR_FORCED_TO_CONTROL     0x1023



#define PARAMETERS_ARRAY_LENGTH 2
#define PARAMETER_ARRAY_DATA_READ_FROM_HEATPUMP 0
#define PARAMETER_ARRAY_DATA_SEND_TO_DISPLAY    1

#define ERROR_VALUE_SIGNED_INT      INT16_MIN
#define ERROR_VALUE_UNSIGNED_INT    UINT16_MAX

// Known parameters
#define REGISTERS_AMOUNT_REAL_TIME_DATA_STATUSSEN  64   // 0x0000?0x03F  = 64 registers
#define REGISTERS_AMOUNT_REAL_TIME_DATA            192  // 0x0040?0x00FF = 192 registers
#define REGISTERS_AMOUNT_UNIT_SYSTEM_PARAMETERS    512  // 0x0100?0x02FF = 512 registers
#define REGISTERS_AMOUNT_USER_PARAMETERS           48   // 0x0300?0x032F = 48 registers
#define REGISTERS_AMOUNT_USER_ORDER                48   // 0x0330?0x035F = 48 registers
#define REGISTERS_AMOUNT_VERSION_INFORMATION       16   // 0x0360?0x036F = 16 registers
#define REGISTERS_AMOUNT_UNIT_SYSTEM_PARAMETER_L   64   // 0x0800?0x083F = 64 registers
#define REGISTERS_AMOUNT_COIL_ADDRESSES            256  // 0x1000?0x10FF = 256 registers

#define START_ADDRESS_REAL_TIME_DATA_STATUSSEN  0x0000  
#define START_ADDRESS_REAL_TIME_DATA            0x0040  
#define START_ADDRESS_UNIT_SYSTEM_PARAMETERS    0x0100  
#define START_ADDRESS_USER_PARAMETERS           0x0300   
#define START_ADDRESS_USER_ORDER                0x0330   
#define START_ADDRESS_VERSION_INFORMATION       0x0360   
#define START_ADDRESS_UNIT_SYSTEM_PARAMETER_L   0x0800   
#define START_ADDRESS_COIL_ADDRESSES            0x1000  

// Unknown parameters
#define REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_1    0x30   
#define REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_2    0x64
#define REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_3    0x64
#define REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_4    0x4D
#define REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_5    0x4D
#define REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_6    0x5F
#define REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_7    0x5F
#define REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_8    0x10
#define REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_9    0x10

#define START_ADDRESS_UNKNOWN_PARAMTERS_1   0x0370  
#define START_ADDRESS_UNKNOWN_PARAMTERS_2   0x0400           
#define START_ADDRESS_UNKNOWN_PARAMTERS_3   0x0600   
#define START_ADDRESS_UNKNOWN_PARAMTERS_4   0x0464           
#define START_ADDRESS_UNKNOWN_PARAMTERS_5   0x0664                
#define START_ADDRESS_UNKNOWN_PARAMTERS_6   0x04B1       
#define START_ADDRESS_UNKNOWN_PARAMTERS_7   0x06B1   
#define START_ADDRESS_UNKNOWN_PARAMTERS_8   0x0840  
#define START_ADDRESS_UNKNOWN_PARAMTERS_9   0x0880


#define MAX_SETTINGS 20


extern uint16_t RealTimeDataStatussen  [REGISTERS_AMOUNT_REAL_TIME_DATA_STATUSSEN] [PARAMETERS_ARRAY_LENGTH]; 
// =
// {{0,1}, 
//  {4,5}, 
// ... etc
//  {8,9}};
extern uint16_t RealTimeData           [REGISTERS_AMOUNT_REAL_TIME_DATA]           [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UnitSystemParameters   [REGISTERS_AMOUNT_UNIT_SYSTEM_PARAMETERS]   [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UserParameters         [REGISTERS_AMOUNT_USER_PARAMETERS]          [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UserOrder              [REGISTERS_AMOUNT_USER_ORDER]               [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t VersionInformation     [REGISTERS_AMOUNT_VERSION_INFORMATION]      [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UnitSystemParameterL   [REGISTERS_AMOUNT_UNIT_SYSTEM_PARAMETER_L]  [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t CoilAddresses          [REGISTERS_AMOUNT_COIL_ADDRESSES]           [PARAMETERS_ARRAY_LENGTH]; 

extern uint16_t UnknownParameters1     [REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_1] [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UnknownParameters2     [REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_2] [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UnknownParameters3     [REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_3] [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UnknownParameters4     [REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_4] [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UnknownParameters5     [REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_5] [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UnknownParameters6     [REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_6] [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UnknownParameters7     [REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_7] [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UnknownParameters8     [REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_8] [PARAMETERS_ARRAY_LENGTH]; 
extern uint16_t UnknownParameters9     [REGISTERS_AMOUNT_UNKNOWN_PARAMTERS_9] [PARAMETERS_ARRAY_LENGTH]; 

typedef enum
{
    SETTING_SEND_STATUS_EMPTY=0,
    SETTING_SEND_STATUS_IDLE,
    SETTING_SEND_STATUS_SETTING_FILLED,  
    SETTING_SEND_STATUS_SETTING_IS_SENT,
    SETTING_SEND_STATUS_SETTING_IS_ECHOED, 
} SETTING_SEND_STATUS;

typedef struct
{
    SETTING_SEND_STATUS settingStatus;
    uint8_t modbusDeviceAddress;
    uint8_t modbusCommand;
    uint16_t modbusWriteRegister;
    uint16_t modbusWriteData;
} MANUAL_SETTING;

extern MANUAL_SETTING Setting;

//extern int16_t SetpointHeating;
//extern int16_t SetpointHotWater;

void ConfirmSettingIsEchoed(uint16_t reg, uint16_t data);
void ChangeHeatpumpSetting(uint16_t reg, uint16_t data);
void SetDataInArrays(uint16_t reg, uint16_t data);
void SetDataInDisplayArray(uint16_t address, uint16_t data);

MANUAL_SETTING PopFirstSetting(void);
void ChangeFirstSettingStatus(SETTING_SEND_STATUS newStatus);
void SetDataInArraysAtStartup(void);

#endif 