#ifndef _SHIFTREGISTERS_H    /* Guard against multiple inclusion */
#define _SHIFTREGISTERS_H

#define SHIFT_REGISTERS_AMOUNT 2
#define BITS_PER_SHIFT_REGISTER 8
#define TOTAL_OUTPUTS (BITS_PER_SHIFT_REGISTER * SHIFT_REGISTERS_AMOUNT)

#define SMALL_DELAY_NOP_AMOUNT 15
#define DELAY_NOP_AMOUNT 30

#define YELLOW_LED_BOTTOM_LEFT  1
#define YELLOW_LED_TOP_LEFT     2
#define GREEN_LED_TOP_LEFT      3
#define GREEN_LED_BOTTOM_LEFT   4

#define YELLOW_LED_BOTTOM_MID   5
#define YELLOW_LED_TOP_MID      6
#define GREEN_LED_TOP_MID       7
#define GREEN_LED_BOTTOM_MID    9

#define YELLOW_LED_BOTTOM_RIGHT 10
#define YELLOW_LED_TOP_RIGHT    11
#define GREEN_LED_TOP_RIGHT     12
#define GREEN_LED_BOTTOM_RIGHT  13



#define LED_TX_BATTERY YELLOW_LED_TOP_LEFT
#define LED_RX_BATTERY GREEN_LED_TOP_LEFT

#define LED_TX_SMART_ENERGY_METER YELLOW_LED_BOTTOM_LEFT
#define LED_RX_SMART_ENERGY_METER GREEN_LED_BOTTOM_LEFT 

#define LED_TX_INVERTER YELLOW_LED_TOP_MID
#define LED_RX_INVERTER GREEN_LED_TOP_MID

#define LED_TX_HEATPUMP_BOILER YELLOW_LED_BOTTOM_MID
#define LED_RX_HEATPUMP_BOILER GREEN_LED_BOTTOM_MID 

#define LED_TX_HEATPUMP YELLOW_LED_TOP_RIGHT
#define LED_RX_HEATPUMP GREEN_LED_TOP_RIGHT

#define LED_TX_DISPLAY YELLOW_LED_BOTTOM_RIGHT
#define LED_RX_DISPLAY GREEN_LED_BOTTOM_RIGHT

void InitShiftRegisters(void);
void SetOutput(uint16_t outputNumber, bool state) ;
void ResetShiftRegisters(void);


#endif /* _HEATPUMP_H */